services:
  xe:
    container_name: ${XE_CONTAINER_NAME:-xe}
    build:
      context: .
      # dockerfile: ./alpine-3.11/Dockerfile
      dockerfile: ./debian-buster/Dockerfile
    # command: ["sleep", "5s;", "composer", "run"]
    # command: >
    #   /bin/sh -c "
    #     sleep 5s;
    #     composer run;
    #   "
    ports:
      - "${XE_PORT:-8270}:80"
    environment:
      ## install
      # - APP_ENV=production
      # - "APP_NAME=XE Website"
      # - "APP_URL=http://localhost"
      # - CACHE_DRIVER=redis
      # - REDIS_HOST=redis
      # - REDIS_PORT=6379
      # - REDIS_PASSWORD=password

      # - "SITE_URL=http://localhost"
      # - "SITE_TIMEZONE=Asia/Seoul"
      # - SITE_LOCALE=ko
      # - ADMIN_EMAIL=admin@geek.re.kr
      # - ADMIN_PASSWORD=password
      # - ADMIN_DISPLAY_NAME=Admin
      # # - DB_CONNECTION=mysql
      # - DB_DRIVER=mysql
      # - DB_HOST=mariadb
      # - DB_PORT=3306
      # - DB_DATABASE=xe_db
      # - DB_USERNAME=root
      # - DB_PASSWORD=password
      # # - DB_PREFIX=

      # xpressengine3 env
      - APP_ENV=production
      - "APP_NAME=XE Website"
      - APP_DEBUG=false
      - APP_URL=http://localhost
      - APP_TIMEZONE=Asia/Seoul
      - APP_LOG=daily
      - APP_LOG_LEVEL=info

      # file/redis/memcached
      ## file
      # - CACHE_DRIVER=file
      ## memcached
      # - CACHE_DRIVER=memcached
      # - MEMCACHED_PERSISTENT_ID=
      # - MEMCACHED_HOST=127.0.0.1
      # - MEMCACHED_PORT=11211
      #- MEMCACHED_USERNAME=
      #- MEMCACHED_PASSWORD=
      ## redis
      - CACHE_DRIVER=${CACHE_DRIVER:-redis}
      - REDIS_HOST=${REDIS_HOST:-redis}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - REDIS_PASSWORD=${REDIS_PASSWORD:-password}

      # google/naver
      # - CAPTCHA_DRIVER=google
      # - CAPTCHA_APIS_GOOGLE_SITEKEY
      # - CAPTCHA_APIS_GOOGLE_SECRET
      # - CAPTCHA_APIS_NAVER_CLIENT_ID
      # - CAPTCHA_APIS_NAVER_SECRET

      # sqlite/mysql
      - DB_CONNECTION=${DB_CONNECTION:-mysql}
      - DB_DATABASE=${DB_DATABASE:-xe_db}
      - DB_HOST=${DB_HOST:-mariadb}
      - DB_PORT=${DB_PORT:-3306}
      - DB_USERNAME=${DB_USERNAME:-root}
      - DB_PASSWORD=${DB_PASSWORD:-password}
      - DB_PREFIX=${DB_PREFIX:-}

      # local/s3/rackspace/ftp
      - FILESYSTEM_DRIVER=local
      # - FILESYSTEM_CLOUD=s3
      # - AWS_KEY
      # - AWS_SECRET
      # - AWS_REGION
      # - ARG AWS_BUCKET

      # smtp/sendmail/mailgun/mandrill,ses,sparkport,log,array
      # - MAIL_DERIVER=smtp
      # - MAIL_HOST=smtp.mailgun.org
      # - MAIL_PORT=587
      # - MAIL_FROM_ADDRESS
      # - MAIL_FROM_NAME
      # - MAIL_ENCRYPTION=tls
      # - MAIL_USERNAME
      # - MAIL_PASSWORD
      ## mailgun
      # - MAILGUN_DOMAIN
      # - MAILGUN_SECRET
      ## ses
      # - SES_KEY
      # - SES_SECRET
      # - SES_REGION
      ## sparkpost
      # - SPARKPOST_SECRET
      ## stripe
      # - STRIPE_KEY
      # - STRIPE_SECRET

      # file/cookie/database/apc/memcached/redis/array
      - SESSION_DRIVER=redis

      # sync/database/beanstalkd/sqs/redis/null
      - QUEUE_DRIVER=redis

    depends_on:
      - mariadb
      - redis

  redis:
    image: redis:8.2-alpine
    container_name: ${REDIS_CONTAINER_NAME:-xe-redis}
    restart: always
    ports:
      - "${REDIS_PORT:-6379}:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD:-password}
    volumes:
      - redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  mariadb:
    image: mariadb:11.8
    container_name: ${MARIADB_CONTAINER_NAME:-xe-mariadb}
    restart: always
    ports:
      - "${DB_PORT:-3306}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-password}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-xe_db}
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5

  # mysql:
  #   image: mysql
  #   container_name: mysql
  #   restart: always
  #   ports:
  #     - 3306:3306
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=password
  #     - MYSQL_DATABASE=xe_db

  # minio:
  #   image: minio/minio
volumes:
  redis:
