services:
  frontend:
    build:
      context: .
      dockerfile: frontend-tsboard.dockerfile
    ports:
      - "8095:80"
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: backend-goapi.dockerfile
    ports:
      - "3100:3100"
    environment:
      - DATABASE_URL=${DATABASE_URL:-mysql://root:example@db:3306/tsboard}
    depends_on:
      - db

  db:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: tsboard
    ports:
      - "3307:3306"
