services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./app:/var/www/html
#      - ./app:/var/www/public
      - ./nginx/php-web.conf:/etc/nginx/conf.d/default.conf
      - ./.nginx.conf:/etc/nginx/conf.d/.nginx.conf
    environment:
      - G5_DOMAIN=localhost:${NGINX_PORT:-8150}
    ports:
      - "${NGINX_PORT:-8150}:80"
    networks:
      - code-network
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: gnuboard5-fpm.dockerfile
    image: gnuboard5:latest
    container_name: gnuboard5
    volumes:
      - ./app:/var/www/html
#      - ./app:/var/www
#      - ./app:/var/www/public
    environment:
      - G5_DOMAIN=localhost:${NGINX_PORT:-8150}
#      - G5_MYSQL_HOST=mariadb
#      - G5_MYSQL_USER=user01
#      - G5_MYSQL_PASSWORD=passw0rd
#      - G5_MYSQL_DB=db01
    networks:
      - code-network
      - db-network
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:11.8
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-rootpass}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-db01}
      - MYSQL_USER=${MYSQL_USER:-user01}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-passw0rd}
    volumes:
      - db:/var/lib/mysql
    networks:
      - db-network
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mariadb
    ports:
      - "${PHPMYADMIN_PORT:-8201}:80"
    environment:
      PMA_USER: ${PMA_USER:-root}
      PMA_PASSWORD: ${PMA_PASSWORD:-rootpass}
      PMA_HOST: mariadb
    networks:
      - db-network

networks:
  code-network:
  db-network:

volumes:
  db:
