services:
  # https://hub.docker.com/r/gollumwiki/gollum
  gollum:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${GOLLUM_CONTAINER_NAME:-gollum}
    # image: gollumwiki/gollum
    restart: always
    ports:
      - "${GOLLUM_PORT:-8170}:4567"
    volumes:
      # - ./wiki:/wiki
      - ./docker-entrypoint.sh:/docker-entrypoint.sh
      - gollum:/wiki
    entrypoint: ["/docker-entrypoint.sh"]
    command: ["gollum", "/wiki"]
    # command: ["gollum", "/home/www-data"]
    depends_on:
      - dollum
  dollum:
    image: busybox
    volumes:
      - ./dollum-entrypoint.sh:/entrypoint.sh
      - gollum:/wiki
    entrypoint: ["sh", "-C", "/entrypoint.sh"]

volumes:
  gollum:
