services:
  jenkins:
    image: jenkins/jenkins:lts-jdk21
    container_name: ${JENKINS_CONTAINER_NAME:-jenkins}
    environment:
      - TZ=${TZ:-Asia/Seoul}
    user: root
    privileged: true
    ports:
      - "${JENKINS_HTTP_PORT:-8180}:8080"
      - "${JENKINS_AGENT_PORT:-50000}:50000"
    volumes:
      - ./tmp/jenkins/config:/var/jenkins_home
#      - /var/run/docker.sock:/var/run/docker.sock
