services:

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-wiki}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-wikijsrocks}
      POSTGRES_USER: ${POSTGRES_USER:-wikijs}
    logging:
      driver: "none"
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-wikijs} -d ${POSTGRES_DB:-wiki}"]
      interval: 10s
      timeout: 5s
      retries: 5

  wiki:
    image: ghcr.io/requarks/wiki:2
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_TYPE: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${POSTGRES_USER:-wikijs}
      DB_PASS: ${POSTGRES_PASSWORD:-wikijsrocks}
      DB_NAME: ${POSTGRES_DB:-wiki}
    restart: unless-stopped
    ports:
      - "80:3000"

volumes:
  db-data: