services:
  uptime-kuma:
    image: louislam/uptime-kuma:${UPTIME_KUMA_VERSION:-1}
    container_name: uptime-kuma
    restart: always
    ports:
      - "${WEB_PORT:-3011}:3001"
    environment:
      TZ: Asia/Seoul
    volumes:
      - uptime-kuma-data:/app/data
    networks:
      - uptime-kuma-network

networks:
  uptime-kuma-network:
    driver: bridge

volumes:
  uptime-kuma-data:
